export const SET_USER_STATUS = 'PROFILE_SET_USER_STATUS';
export const SET_USER_AVATAR = 'PROFILE_SET_USER_AVATAR';
export const SET_PROFILE_UPDATING_STATUS = 'PROFILE_SET_PROFILE_UPDATING_STATUS';
export const SET_USER_PROFILE = 'PROFILE_SET_USER_PROFILE';